-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied


-- MySQL Script generated by MySQL Workbench
-- sex 13 mar 2020 15:07:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pep` ;
USE `pep` ;

-- -----------------------------------------------------
-- Table `pep`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pep`.`locals` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `res_id` VARCHAR(255) NOT NULL,
  `res_cnes` VARCHAR(255) NOT NULL,
  `res_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `res_id_UNIQUE` (`res_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pep`.`user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `pep`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_sso` VARCHAR(255) NULL,
  `res_pro_mpi` VARCHAR(255) NOT NULL,
  `res_pro_name` VARCHAR(255) NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `created_by` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pep`.`audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pep`.`audit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `what` VARCHAR(255) NULL,
  `who` VARCHAR(255) NULL,
  `when` DATETIME NULL,
  `where` VARCHAR(255) NULL,
  `how` VARCHAR(45) NULL,
  `how_much` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pep`.`user_has_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pep`.`user_local` (
  `user_id` INT UNSIGNED NOT NULL,
  `local_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `local_id`),
  INDEX `fk_user_has_local_local1_idx` (`local_id` ASC),
  INDEX `fk_user_has_local_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_local_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pep`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_local_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `pep`.`local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back
DROP TABLE local;
DROP TABLE user;
DROP TABLE audit;
DROP TABLE user_has_local;
